-- =============================================================================
-- Plataforma de Gestión de Proyectos FCI - Universidad de Guayaquil
-- Tabla unificada perfiles_usuario (rol inline), RLS diferenciada por rol,
-- función auxiliar sin recursión y trigger de registro automático.
-- Aplica/re-aplica este script en Supabase SQL Editor.
-- =============================================================================

-- 1. Tipo ENUM para roles
DO $$ BEGIN
  CREATE TYPE public.tipo_rol AS ENUM (
    'administradora', 'investigadora', 'formadora', 'mujer_emprendedora', 'institucion_aliada'
  );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 2. Tabla unificada PERFILES (rol incluido directamente, sin tabla separada)
CREATE TABLE IF NOT EXISTS public.perfiles_usuario (
  id                      UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre_completo         TEXT,
  email                   TEXT,
  telefono                TEXT,
  breve_descripcion       TEXT,
  rol                     public.tipo_rol,
  linkedin                TEXT,
  fecha_registro          TIMESTAMP WITH TIME ZONE DEFAULT now(),
  fecha_actualizacion     TIMESTAMP WITH TIME ZONE DEFAULT now(),
  ultimo_acceso           TIMESTAMP WITH TIME ZONE,
  avatar_url              TEXT,
  notificaciones_activas  BOOLEAN DEFAULT TRUE,
  cuenta_activa           BOOLEAN DEFAULT TRUE
);

-- Si la tabla ya existía sin la columna rol, agregarla
ALTER TABLE public.perfiles_usuario ADD COLUMN IF NOT EXISTS rol public.tipo_rol;

-- 3. Tabla roles_usuario (se mantiene para compatibilidad y migración)
CREATE TABLE IF NOT EXISTS public.roles_usuario (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario       UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  rol              public.tipo_rol NOT NULL,
  fecha_asignacion TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  UNIQUE (id_usuario, rol)
);

-- Migrar roles existentes de roles_usuario → perfiles_usuario.rol
UPDATE public.perfiles_usuario p
SET rol = r.rol
FROM public.roles_usuario r
WHERE r.id_usuario = p.id
  AND p.rol IS NULL;

-- 4. Habilitar Row Level Security
ALTER TABLE public.perfiles_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles_usuario    ENABLE ROW LEVEL SECURITY;

-- 5. Función auxiliar: devuelve el rol del usuario autenticado SIN recursión RLS
--    (SECURITY DEFINER omite las políticas al consultarse a sí misma)
CREATE OR REPLACE FUNCTION public.get_my_rol()
RETURNS public.tipo_rol
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT p.rol FROM public.perfiles_usuario p WHERE p.id = auth.uid() LIMIT 1),
    (SELECT r.rol FROM public.roles_usuario r WHERE r.id_usuario = auth.uid() ORDER BY r.fecha_asignacion DESC LIMIT 1)
  );
$$;

-- Sincroniza el rol inline desde roles_usuario para usuarios existentes
UPDATE public.perfiles_usuario p
SET rol = r.rol
FROM (
  SELECT DISTINCT ON (id_usuario) id_usuario, rol
  FROM public.roles_usuario
  ORDER BY id_usuario, fecha_asignacion DESC
) r
WHERE p.id = r.id_usuario
  AND (p.rol IS NULL OR p.rol <> r.rol);

-- 6. POLÍTICAS RLS — perfiles_usuario
-- Limpiar políticas anteriores
DROP POLICY IF EXISTS "perfiles_select_propio"  ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_select_admin"   ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_insert_propio"  ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_update_propio"  ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_update_admin"   ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_delete_admin"   ON public.perfiles_usuario;

-- Cada usuario lee su propio perfil
CREATE POLICY "perfiles_select_propio" ON public.perfiles_usuario
  FOR SELECT USING (id = auth.uid());

-- Administradora lee TODOS los perfiles
CREATE POLICY "perfiles_select_admin" ON public.perfiles_usuario
  FOR SELECT USING (public.get_my_rol() = 'administradora');

-- Cada usuario inserta su propio perfil (trigger de registro)
CREATE POLICY "perfiles_insert_propio" ON public.perfiles_usuario
  FOR INSERT WITH CHECK (id = auth.uid());

-- Cada usuario actualiza su propio perfil
CREATE POLICY "perfiles_update_propio" ON public.perfiles_usuario
  FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- Administradora actualiza CUALQUIER perfil
CREATE POLICY "perfiles_update_admin" ON public.perfiles_usuario
  FOR UPDATE USING (public.get_my_rol() = 'administradora');

-- Administradora puede desactivar (eliminar) perfiles
CREATE POLICY "perfiles_delete_admin" ON public.perfiles_usuario
  FOR DELETE USING (public.get_my_rol() = 'administradora');

-- 7. POLÍTICAS RLS — roles_usuario
DROP POLICY IF EXISTS "roles_select_propio" ON public.roles_usuario;
DROP POLICY IF EXISTS "roles_select_admin"  ON public.roles_usuario;
DROP POLICY IF EXISTS "roles_insert_admin"  ON public.roles_usuario;
DROP POLICY IF EXISTS "roles_update_admin"  ON public.roles_usuario;
DROP POLICY IF EXISTS "roles_delete_admin"  ON public.roles_usuario;

CREATE POLICY "roles_select_propio" ON public.roles_usuario
  FOR SELECT USING (id_usuario = auth.uid());

CREATE POLICY "roles_select_admin" ON public.roles_usuario
  FOR SELECT USING (public.get_my_rol() = 'administradora');

CREATE POLICY "roles_insert_admin" ON public.roles_usuario
  FOR INSERT WITH CHECK (public.get_my_rol() = 'administradora');

CREATE POLICY "roles_update_admin" ON public.roles_usuario
  FOR UPDATE USING (public.get_my_rol() = 'administradora');

CREATE POLICY "roles_delete_admin" ON public.roles_usuario
  FOR DELETE USING (public.get_my_rol() = 'administradora');

-- 8. Trigger: crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.perfiles_usuario (id, nombre_completo, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'nombre_completo', NULL),
    NEW.email
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();
