-- =============================================================================
-- Kawsay Emprende Guayaquil - esquema normalizado de roles, perfiles y encuesta
-- Aplica este script despues de 001_auth_setup.sql en Supabase SQL Editor.
-- Es idempotente y conserva compatibilidad con columnas antiguas mientras migras.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN
  CREATE TYPE public.tipo_rol AS ENUM (
    'administradora',
    'investigadora',
    'formadora',
    'mujer_emprendedora',
    'institucion_aliada'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.estado_encuesta AS ENUM ('borrador', 'enviada', 'validada', 'anulada');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo public.tipo_rol NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO public.roles (codigo, nombre, descripcion)
VALUES
  ('administradora', 'Administradora', 'Acceso completo a gestion, configuracion y reportes.'),
  ('investigadora', 'Investigadora', 'Analisis academico, validacion metodologica y evidencia cientifica.'),
  ('formadora', 'Formadora', 'Gestion y seguimiento de modulos formativos asignados.'),
  ('mujer_emprendedora', 'Mujer emprendedora', 'Participante que responde encuestas y cursa la malla formativa.'),
  ('institucion_aliada', 'Institucion aliada', 'Consulta resultados generales, avance e indicadores institucionales.')
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    activo = TRUE;

CREATE TABLE IF NOT EXISTS public.permisos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  modulo TEXT NOT NULL,
  descripcion TEXT
);

CREATE TABLE IF NOT EXISTS public.roles_permisos (
  id_rol BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE CASCADE,
  id_permiso BIGINT NOT NULL REFERENCES public.permisos(id) ON DELETE CASCADE,
  PRIMARY KEY (id_rol, id_permiso)
);

CREATE TABLE IF NOT EXISTS public.perfiles_usuario (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre_completo TEXT,
  email TEXT UNIQUE,
  telefono TEXT,
  breve_descripcion TEXT,
  linkedin TEXT,
  avatar_url TEXT,
  parroquia TEXT,
  sector TEXT,
  autoidentificacion_cultural TEXT,
  fecha_nacimiento DATE,
  fecha_registro TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  ultimo_acceso TIMESTAMPTZ,
  notificaciones_activas BOOLEAN NOT NULL DEFAULT TRUE,
  cuenta_activa BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE public.perfiles_usuario ADD COLUMN IF NOT EXISTS parroquia TEXT;
ALTER TABLE public.perfiles_usuario ADD COLUMN IF NOT EXISTS sector TEXT;
ALTER TABLE public.perfiles_usuario ADD COLUMN IF NOT EXISTS autoidentificacion_cultural TEXT;
ALTER TABLE public.perfiles_usuario ADD COLUMN IF NOT EXISTS fecha_nacimiento DATE;
ALTER TABLE public.perfiles_usuario ADD COLUMN IF NOT EXISTS cuenta_activa BOOLEAN DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS public.roles_usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  id_rol BIGINT REFERENCES public.roles(id) ON DELETE RESTRICT,
  rol public.tipo_rol,
  fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  asignado_por UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.roles_usuario ADD COLUMN IF NOT EXISTS id_rol BIGINT REFERENCES public.roles(id) ON DELETE RESTRICT;
ALTER TABLE public.roles_usuario ADD COLUMN IF NOT EXISTS rol public.tipo_rol;
ALTER TABLE public.roles_usuario ADD COLUMN IF NOT EXISTS asignado_por UUID REFERENCES auth.users(id) ON DELETE SET NULL;

UPDATE public.roles_usuario ru
SET id_rol = r.id
FROM public.roles r
WHERE ru.id_rol IS NULL
  AND ru.rol = r.codigo;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'perfiles_usuario'
      AND column_name = 'rol'
  ) THEN
    EXECUTE $sql$
      INSERT INTO public.roles_usuario (id_usuario, id_rol, rol, fecha_asignacion)
      SELECT p.id, r.id, p.rol, now()
      FROM public.perfiles_usuario p
      JOIN public.roles r ON r.codigo = p.rol
      WHERE p.rol IS NOT NULL
        AND NOT EXISTS (
          SELECT 1 FROM public.roles_usuario ru WHERE ru.id_usuario = p.id
        )
    $sql$;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS roles_usuario_un_rol_por_usuario
  ON public.roles_usuario (id_usuario);

CREATE OR REPLACE VIEW public.v_perfiles_usuario_con_rol AS
SELECT
  p.id,
  p.nombre_completo,
  p.email,
  p.telefono,
  p.breve_descripcion,
  p.linkedin,
  p.avatar_url,
  p.parroquia,
  p.sector,
  p.autoidentificacion_cultural,
  p.fecha_nacimiento,
  p.fecha_registro,
  p.fecha_actualizacion,
  p.ultimo_acceso,
  p.notificaciones_activas,
  p.cuenta_activa,
  r.codigo AS rol,
  r.nombre AS rol_nombre
FROM public.perfiles_usuario p
LEFT JOIN public.roles_usuario ru ON ru.id_usuario = p.id
LEFT JOIN public.roles r ON r.id = ru.id_rol;

CREATE OR REPLACE FUNCTION public.get_my_rol()
RETURNS public.tipo_rol
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT r.codigo
  FROM public.perfiles_usuario p
  LEFT JOIN public.roles_usuario ru ON ru.id_usuario = p.id
  LEFT JOIN public.roles r ON r.id = ru.id_rol
  WHERE p.id = auth.uid()
  LIMIT 1;
$$;

CREATE TABLE IF NOT EXISTS public.encuestas_iniciales (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  id_participante UUID NOT NULL REFERENCES public.perfiles_usuario(id) ON DELETE CASCADE,
  estado public.estado_encuesta NOT NULL DEFAULT 'borrador',
  fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT now(),
  fecha_envio TIMESTAMPTZ,
  fecha_validacion TIMESTAMPTZ,
  validada_por UUID REFERENCES public.perfiles_usuario(id) ON DELETE SET NULL,
  observaciones_validacion TEXT,
  UNIQUE (id_participante)
);

CREATE TABLE IF NOT EXISTS public.encuesta_consentimiento (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  acepta_participar BOOLEAN NOT NULL DEFAULT FALSE,
  acepta_uso_academico BOOLEAN NOT NULL DEFAULT FALSE,
  acepta_confidencialidad BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_aceptacion TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.encuesta_datos_sociodemograficos (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  parroquia TEXT,
  sector_especifico TEXT,
  lugar_procedencia TEXT,
  edad INTEGER CHECK (edad IS NULL OR edad BETWEEN 12 AND 120),
  nivel_instruccion TEXT,
  estado_civil TEXT,
  dependientes_economicos INTEGER CHECK (dependientes_economicos IS NULL OR dependientes_economicos >= 0),
  autoidentificacion_cultural TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_informacion_emprendimiento (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  tiempo_emprendimiento TEXT,
  sector_principal TEXT,
  sector_otro TEXT,
  numero_trabajadores INTEGER CHECK (numero_trabajadores IS NULL OR numero_trabajadores >= 0),
  ingreso_mensual_aproximado NUMERIC(12,2),
  descripcion_emprendimiento TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_gestion_empresarial (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  tiene_ruc_o_permisos BOOLEAN,
  paga_impuestos_o_renueva_permisos BOOLEAN,
  contrata_trabajadores BOOLEAN,
  forma_contratacion TEXT,
  registra_compras_materiales_ventas BOOLEAN,
  organiza_tareas_y_metas BOOLEAN,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_finanzas (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  ha_solicitado_credito BOOLEAN,
  instituciones_financieras TEXT,
  ahorra_o_reinvierte BOOLEAN,
  registra_entradas_salidas BOOLEAN,
  forma_define_precios TEXT,
  necesita_capacitacion_financiera BOOLEAN,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_marketing_ventas (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  formas_promocion TEXT,
  usa_ferias_mercados BOOLEAN,
  usa_redes_sociales BOOLEAN,
  atencion_cliente TEXT,
  calidad_productos_servicios TEXT,
  integra_cultura_tradiciones BOOLEAN,
  adapta_productos_clientes BOOLEAN,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_tecnologia_digitalizacion (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  tiene_dispositivo_internet BOOLEAN,
  dispositivos TEXT,
  usa_whatsapp BOOLEAN,
  usa_facebook BOOLEAN,
  usa_instagram BOOLEAN,
  usa_tiktok BOOLEAN,
  usa_pagos_digitales BOOLEAN,
  usa_comercio_en_linea BOOLEAN,
  usa_herramientas_ia BOOLEAN,
  dificultades_tecnologia TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_capital_social_redes (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  participo_capacitaciones BOOLEAN,
  tipos_capacitaciones TEXT,
  organizaciones_capacitadoras TEXT,
  recibio_apoyo_no_capacitacion BOOLEAN,
  tipo_apoyo_recibido TEXT,
  participa_redes_apoyo BOOLEAN,
  redes_comunitarias TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_aspectos_personales_familiares (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  equilibrio_familia_negocio TEXT,
  recibe_apoyo_familiar BOOLEAN,
  tipo_apoyo_familiar TEXT,
  cuida_salud_mientras_trabaja BOOLEAN,
  seguridad_para_continuar TEXT,
  motivacion_para_continuar TEXT,
  observaciones TEXT
);

CREATE TABLE IF NOT EXISTS public.encuesta_barreras_oportunidades (
  id_encuesta UUID PRIMARY KEY REFERENCES public.encuestas_iniciales(id) ON DELETE CASCADE,
  barreras_principales TEXT,
  dificultad_financiamiento BOOLEAN,
  dificultad_tramites BOOLEAN,
  falta_apoyo_familiar BOOLEAN,
  falta_capacitacion BOOLEAN,
  dificultad_clientes_mercados BOOLEAN,
  oportunidades_crecimiento TEXT,
  interes_nuevas_capacitaciones BOOLEAN,
  interes_tecnologia BOOLEAN,
  interes_redes_apoyo BOOLEAN,
  interes_nuevos_mercados BOOLEAN,
  interes_innovacion BOOLEAN,
  interes_cultura_tradicional BOOLEAN
);

CREATE INDEX IF NOT EXISTS encuestas_iniciales_participante_idx
  ON public.encuestas_iniciales (id_participante);
CREATE INDEX IF NOT EXISTS encuestas_iniciales_estado_idx
  ON public.encuestas_iniciales (estado);
CREATE INDEX IF NOT EXISTS encuesta_sociodemograficos_parroquia_idx
  ON public.encuesta_datos_sociodemograficos (parroquia);
CREATE INDEX IF NOT EXISTS encuesta_emprendimiento_sector_idx
  ON public.encuesta_informacion_emprendimiento (sector_principal);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rol_inicial public.tipo_rol;
  rol_id BIGINT;
BEGIN
  rol_inicial := COALESCE((NEW.raw_user_meta_data ->> 'rol_asignado')::public.tipo_rol, 'mujer_emprendedora');

  INSERT INTO public.perfiles_usuario (id, nombre_completo, email)
  VALUES (
    NEW.id,
    NULLIF(NEW.raw_user_meta_data ->> 'nombre_completo', ''),
    NEW.email
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email,
      nombre_completo = COALESCE(public.perfiles_usuario.nombre_completo, EXCLUDED.nombre_completo),
      fecha_actualizacion = now();

  SELECT id INTO rol_id FROM public.roles WHERE codigo = rol_inicial LIMIT 1;

  INSERT INTO public.roles_usuario (id_usuario, id_rol, rol)
  VALUES (NEW.id, rol_id, rol_inicial)
  ON CONFLICT (id_usuario) DO UPDATE
  SET id_rol = EXCLUDED.id_rol,
      rol = EXCLUDED.rol,
      fecha_asignacion = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles_permisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.perfiles_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuestas_iniciales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_consentimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_datos_sociodemograficos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_informacion_emprendimiento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_gestion_empresarial ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_finanzas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_marketing_ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_tecnologia_digitalizacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_capital_social_redes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_aspectos_personales_familiares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.encuesta_barreras_oportunidades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "roles_select_authenticated" ON public.roles;
CREATE POLICY "roles_select_authenticated" ON public.roles
  FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "perfiles_select_propio" ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_select_admin" ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_update_propio" ON public.perfiles_usuario;
DROP POLICY IF EXISTS "perfiles_update_admin" ON public.perfiles_usuario;
CREATE POLICY "perfiles_select_propio" ON public.perfiles_usuario
  FOR SELECT USING (id = auth.uid());
CREATE POLICY "perfiles_select_admin" ON public.perfiles_usuario
  FOR SELECT USING (public.get_my_rol() = 'administradora');
CREATE POLICY "perfiles_update_propio" ON public.perfiles_usuario
  FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY "perfiles_update_admin" ON public.perfiles_usuario
  FOR UPDATE USING (public.get_my_rol() = 'administradora');

DROP POLICY IF EXISTS "roles_usuario_select_propio" ON public.roles_usuario;
DROP POLICY IF EXISTS "roles_usuario_select_admin" ON public.roles_usuario;
DROP POLICY IF EXISTS "roles_usuario_write_admin" ON public.roles_usuario;
CREATE POLICY "roles_usuario_select_propio" ON public.roles_usuario
  FOR SELECT USING (id_usuario = auth.uid());
CREATE POLICY "roles_usuario_select_admin" ON public.roles_usuario
  FOR SELECT USING (public.get_my_rol() = 'administradora');
CREATE POLICY "roles_usuario_write_admin" ON public.roles_usuario
  FOR ALL USING (public.get_my_rol() = 'administradora')
  WITH CHECK (public.get_my_rol() = 'administradora');

DROP POLICY IF EXISTS "encuestas_select_participante" ON public.encuestas_iniciales;
DROP POLICY IF EXISTS "encuestas_select_equipo" ON public.encuestas_iniciales;
DROP POLICY IF EXISTS "encuestas_write_participante" ON public.encuestas_iniciales;
DROP POLICY IF EXISTS "encuestas_write_admin" ON public.encuestas_iniciales;
CREATE POLICY "encuestas_select_participante" ON public.encuestas_iniciales
  FOR SELECT USING (id_participante = auth.uid());
CREATE POLICY "encuestas_select_equipo" ON public.encuestas_iniciales
  FOR SELECT USING (public.get_my_rol() IN ('administradora', 'investigadora'));
CREATE POLICY "encuestas_write_participante" ON public.encuestas_iniciales
  FOR ALL USING (id_participante = auth.uid()) WITH CHECK (id_participante = auth.uid());
CREATE POLICY "encuestas_write_admin" ON public.encuestas_iniciales
  FOR ALL USING (public.get_my_rol() = 'administradora')
  WITH CHECK (public.get_my_rol() = 'administradora');

-- Politicas por bloque: heredan permisos desde la encuesta cabecera.
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'encuesta_consentimiento',
    'encuesta_datos_sociodemograficos',
    'encuesta_informacion_emprendimiento',
    'encuesta_gestion_empresarial',
    'encuesta_finanzas',
    'encuesta_marketing_ventas',
    'encuesta_tecnologia_digitalizacion',
    'encuesta_capital_social_redes',
    'encuesta_aspectos_personales_familiares',
    'encuesta_barreras_oportunidades'
  ]
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_select', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_write', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT USING (
        EXISTS (
          SELECT 1 FROM public.encuestas_iniciales e
          WHERE e.id = id_encuesta
            AND (e.id_participante = auth.uid() OR public.get_my_rol() IN (''administradora'', ''investigadora''))
        )
      )',
      t || '_select',
      t
    );
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL USING (
        EXISTS (
          SELECT 1 FROM public.encuestas_iniciales e
          WHERE e.id = id_encuesta
            AND (e.id_participante = auth.uid() OR public.get_my_rol() = ''administradora'')
        )
      ) WITH CHECK (
        EXISTS (
          SELECT 1 FROM public.encuestas_iniciales e
          WHERE e.id = id_encuesta
            AND (e.id_participante = auth.uid() OR public.get_my_rol() = ''administradora'')
        )
      )',
      t || '_write',
      t
    );
  END LOOP;
END $$;
