export type SurveyQuestion = {
  id: string
  label: string
  type: "text" | "radio" | "checkbox"
  required?: boolean
  options?: string[]
  placeholder?: string
  visibleWhen?: {
    questionId: string
    values: string[]
  }
}

export type SurveyBlock = {
  id: string
  title: string
  description?: string
  questions: SurveyQuestion[]
}

const yesSometimesNo = ["Si", "A veces", "No"]

export const initialSurveyBlocks: SurveyBlock[] = [
  {
    id: "sociodemograficos",
    title: "Datos sociodemograficos",
    questions: [
      {
        id: "parroquia",
        label: "a) En que parroquia se encuentra ubicado su negocio o emprendimiento?",
        type: "radio",
        required: true,
        options: ["Tarqui", "Ximena", "Febres Cordero", "Pascuales", "Letamendi", "9 de octubre", "Ayacucho", "Chongon", "Posorja", "Tenguel", "Otro"],
      },
      {
        id: "sector_especifico",
        label: "b) En que sector especifico (barrio, ciudadela, urbanizacion o cooperativa) esta ubicado su negocio?",
        type: "text",
        required: true,
        placeholder: "Escriba el sector",
      },
      {
        id: "lugar_procedencia",
        label: "c) De que lugar proviene usted (pais/provincia/canton)?",
        type: "text",
        required: true,
        placeholder: "Ej. Ecuador / Guayas / Guayaquil",
      },
      {
        id: "edad_rango",
        label: "d) Edad:",
        type: "radio",
        required: true,
        options: ["Menos de 20 anos", "20 - 29 anos", "30 - 39 anos", "40 - 49 anos", "50 anos o mas"],
      },
      {
        id: "nivel_instruccion",
        label: "e) Cual es el nivel mas alto de instruccion que ha alcanzado?",
        type: "radio",
        required: true,
        options: ["Sin instruccion formal", "Educacion primaria", "Educacion secundaria", "Educacion tecnica / tecnologica", "Educacion universitaria", "Posgrado"],
      },
      {
        id: "estado_civil",
        label: "f) Estado civil:",
        type: "radio",
        required: true,
        options: ["Soltera", "Union de hecho", "Casada", "Separada", "Divorciada", "Viuda"],
      },
      {
        id: "dependientes_economicos",
        label: "g) Cuantos familiares dependen de usted economicamente?",
        type: "radio",
        required: true,
        options: ["Ninguno", "1 - 2", "3 - 4", "5 o mas"],
      },
      {
        id: "autoidentificacion_cultural",
        label: "h) Como se autoidentifica usted cultural o etnicamente?",
        type: "radio",
        required: true,
        options: ["Indigena", "Afroecuatoriana", "Mestiza", "Montubia", "Blanca", "Otro"],
      },
      {
        id: "pueblo_nacionalidad",
        label: "Si se autoidentifica como indigena, especifique su pueblo o nacionalidad:",
        type: "text",
        placeholder: "Respuesta opcional",
        visibleWhen: { questionId: "autoidentificacion_cultural", values: ["Indigena"] },
      },
      {
        id: "autoidentificacion_otro",
        label: "Si selecciono Otro, especifique su autoidentificacion:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "autoidentificacion_cultural", values: ["Otro"] },
      },
      {
        id: "parroquia_otro",
        label: "Si selecciono Otro, especifique la parroquia:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "parroquia", values: ["Otro"] },
      },
    ],
  },
  {
    id: "emprendimiento",
    title: "Informacion del emprendimiento",
    questions: [
      {
        id: "tiempo_emprendimiento",
        label: "i) Tiempo que lleva con su emprendimiento:",
        type: "radio",
        required: true,
        options: ["Menos de 1 ano", "1 - 3 anos", "4 - 6 anos", "7 anos o mas"],
      },
      {
        id: "sector_principal",
        label: "j) Sector principal del emprendimiento:",
        type: "radio",
        required: true,
        options: ["Artesanias / manualidades", "Textiles / confecciones", "Alimentacion / gastronomia", "Comercio (venta de productos)", "Servicios", "Otro"],
      },
      {
        id: "sector_principal_otro",
        label: "Si selecciono Otro, especifique el sector principal:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "sector_principal", values: ["Otro"] },
      },
      {
        id: "numero_trabajadores",
        label: "k) Numero de trabajadores en su emprendimiento (incluyendose):",
        type: "radio",
        required: true,
        options: ["Solo yo", "2 - 3", "4 - 5", "Mas de 5"],
      },
      {
        id: "ingreso_mensual",
        label: "l) Ingreso mensual aproximado del emprendimiento:",
        type: "radio",
        required: true,
        options: ["Menos de 200 USD", "200 - 399 USD", "400 - 699 USD", "700 - 999 USD", "1000 USD o mas"],
      },
    ],
  },
  {
    id: "gestion_empresarial",
    title: "Bloque 1. Gestion empresarial y administrativa",
    description: "Preguntas sobre formalizacion, contratacion, registros y organizacion del negocio.",
    questions: [
      {
        id: "tiene_ruc_permisos",
        label: "1. Actualmente su negocio cuenta con papeles en regla, como RUC o permisos municipales?",
        type: "radio",
        required: true,
        options: ["Si", "No"],
      },
      {
        id: "paga_impuestos_permisos",
        label: "2. Acostumbra a pagar impuestos o renovar permisos de funcionamiento cuando corresponde?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "contrata_trabajadores",
        label: "3. Acostumbra a contratar trabajadores para su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "formalizacion_contratacion",
        label: "Si respondio Si o A veces, indique como suele formalizar normalmente la contratacion:",
        type: "radio",
        required: true,
        options: ["Acuerdo verbal", "Acuerdo escrito sencillo", "Contrato formal", "Apoyo familiar sin contrato", "Otro"],
        visibleWhen: { questionId: "contrata_trabajadores", values: ["Si", "A veces"] },
      },
      {
        id: "formalizacion_contratacion_otro",
        label: "Si selecciono Otro, especifique la forma de contratacion:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "formalizacion_contratacion", values: ["Otro"] },
      },
      {
        id: "registra_compras_ventas",
        label: "4. Acostumbra a llevar o anotar cuantos productos o materiales compra para su negocio y cuantos va vendiendo?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "organiza_metas_tareas",
        label: "5. Acostumbra a definir lo que quiere lograr con su negocio y organiza las tareas necesarias para alcanzarlo?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
    ],
  },
  {
    id: "finanzas",
    title: "Bloque 2. Finanzas y sostenibilidad economica",
    questions: [
      {
        id: "solicita_creditos",
        label: "6. Acostumbra a solicitar creditos, microcreditos o ayudas economicas para su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "institucion_credito",
        label: "Si respondio Si o A veces, indique donde los ha solicitado:",
        type: "radio",
        required: true,
        options: ["Bancos", "Cooperativas de ahorro y credito", "Instituciones publicas", "ONGs u organismos internacionales", "Otro"],
        visibleWhen: { questionId: "solicita_creditos", values: ["Si", "A veces"] },
      },
      {
        id: "institucion_credito_otro",
        label: "Si selecciono Otro, especifique donde solicito apoyo:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "institucion_credito", values: ["Otro"] },
      },
      {
        id: "ahorra_reinvierte",
        label: "7. Acostumbra usted a guardar parte del dinero que gana para volverlo a usar en su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "registra_dinero",
        label: "8. Acostumbra usted a llevar un registro del dinero que entra y sale de su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "define_precios_costos",
        label: "9. Acostumbra usted a poner precios tomando en cuenta costos y ganancia esperada?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
    ],
  },
  {
    id: "marketing_ventas",
    title: "Bloque 3. Marketing y ventas",
    questions: [
      {
        id: "promociona_negocio",
        label: "10. Acostumbra usted a buscar distintas formas de promocionar su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "formas_promocion",
        label: "Si respondio Si o A veces, seleccione cuales utiliza con mas frecuencia:",
        type: "checkbox",
        required: true,
        options: ["Boca a boca", "Ferias o mercados", "Letrero en el local", "Volantes o afiches", "Redes sociales", "Otro"],
        visibleWhen: { questionId: "promociona_negocio", values: ["Si", "A veces"] },
      },
      {
        id: "formas_promocion_otro",
        label: "Si selecciono Otro, especifique la forma de promocion:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "formas_promocion", values: ["Otro"] },
      },
      {
        id: "buena_atencion",
        label: "11. Procura dar una buena atencion a sus clientes para que vuelvan a comprarle?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "cuida_calidad",
        label: "12. Acostumbra a cuidar la calidad de sus productos o servicios para que sean mejores que los de otros negocios?",
        type: "radio",
        required: true,
        options: ["Si", "No", "A veces"],
      },
      {
        id: "integra_cultura",
        label: "13. Acostumbra a dar un toque de su cultura o tradiciones a sus productos o servicios?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "elementos_culturales",
        label: "Si respondio Si o A veces, indique cuales elementos culturales utiliza:",
        type: "checkbox",
        required: true,
        options: ["Comidas y recetas tradicionales", "Artesanias, tejidos o manualidades", "Materiales de la zona", "Musica, danza o peinados propios", "Fiestas, celebraciones o simbolos religiosos", "Agricultura o practicas del campo", "Medicina tradicional", "Turismo comunitario o cultural", "Otro"],
        visibleWhen: { questionId: "integra_cultura", values: ["Si", "A veces"] },
      },
      {
        id: "elementos_culturales_otro",
        label: "Si selecciono Otro, especifique el elemento cultural:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "elementos_culturales", values: ["Otro"] },
      },
      {
        id: "adapta_productos",
        label: "14. Acostumbra a hacer cambios en sus productos o servicios segun lo que piden sus clientes?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
    ],
  },
  {
    id: "tecnologia",
    title: "Bloque 4. Tecnologia y digitalizacion",
    questions: [
      {
        id: "dispositivo_internet",
        label: "15. Cuenta usted con algun dispositivo con acceso a internet para apoyar su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "dispositivos",
        label: "Si respondio Si o A veces, indique cual utiliza con mayor frecuencia:",
        type: "checkbox",
        required: true,
        options: ["Telefono celular / smartphone", "Computadora / laptop", "Tablet", "Otro"],
        visibleWhen: { questionId: "dispositivo_internet", values: ["Si", "A veces"] },
      },
      {
        id: "dispositivos_otro",
        label: "Si selecciono Otro, especifique el dispositivo:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "dispositivos", values: ["Otro"] },
      },
      {
        id: "usa_apps_digitales",
        label: "16. Acostumbra a usar aplicaciones digitales como WhatsApp, Facebook u otros para dar a conocer sus productos?",
        type: "radio",
        options: yesSometimesNo,
        visibleWhen: { questionId: "dispositivo_internet", values: ["Si", "A veces"] },
      },
      {
        id: "apps_utilizadas",
        label: "Si respondio Si o A veces, indique cuales aplicaciones utiliza:",
        type: "checkbox",
        options: ["WhatsApp", "Facebook/Marketplace", "Instagram", "TikTok", "Mercado Libre", "Apps de delivery", "Otro"],
        visibleWhen: { questionId: "usa_apps_digitales", values: ["Si", "A veces"] },
      },
      {
        id: "apps_utilizadas_otro",
        label: "Si selecciono Otro, especifique la aplicacion:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "apps_utilizadas", values: ["Otro"] },
      },
      {
        id: "usa_pagos_digitales",
        label: "17. Acostumbra a usar pagos digitales para cobrar o pagar en su negocio?",
        type: "radio",
        options: yesSometimesNo,
        visibleWhen: { questionId: "dispositivo_internet", values: ["Si", "A veces"] },
      },
      {
        id: "pagos_digitales",
        label: "Si respondio Si o A veces, indique cuales medios de pago utiliza:",
        type: "checkbox",
        options: ["Transferencia bancaria", "PayPhone", "Deuna / boton QR", "Aplicacion del banco movil / banca en linea", "Enlace o boton de pago por redes sociales / WhatsApp", "Otro"],
        visibleWhen: { questionId: "usa_pagos_digitales", values: ["Si", "A veces"] },
      },
      {
        id: "pagos_digitales_otro",
        label: "Si selecciono Otro, especifique el medio de pago:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "pagos_digitales", values: ["Otro"] },
      },
      {
        id: "vende_en_linea",
        label: "18. Acostumbra a vender productos o servicios en plataformas de comercio en linea?",
        type: "radio",
        options: yesSometimesNo,
        visibleWhen: { questionId: "dispositivo_internet", values: ["Si", "A veces"] },
      },
      {
        id: "usa_ia",
        label: "19. Utiliza herramientas de inteligencia artificial (IA) para facilitar la gestion de su negocio?",
        type: "radio",
        options: ["Si", "Un poco", "No"],
        visibleWhen: { questionId: "dispositivo_internet", values: ["Si", "A veces"] },
      },
      {
        id: "actividades_ia",
        label: "Si respondio Si o Un poco, indique en que actividades usa IA:",
        type: "checkbox",
        options: ["Responder a clientes", "Hacer anuncios o publicaciones", "Poner precios o calcular cuentas", "Organizar pedidos o productos", "Otro"],
        visibleWhen: { questionId: "usa_ia", values: ["Si", "Un poco"] },
      },
      {
        id: "actividades_ia_otro",
        label: "Si selecciono Otro, especifique el uso de IA:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "actividades_ia", values: ["Otro"] },
      },
      {
        id: "dificultad_tecnologia",
        label: "20. Cual es la principal dificultad que ha tenido para usar tecnologia en la gestion de su negocio?",
        type: "radio",
        required: true,
        options: ["No tengo internet o es muy caro", "No se usar bien las aplicaciones", "No tengo tiempo para aprender", "No tengo quien me ensene"],
      },
    ],
  },
  {
    id: "redes_apoyo",
    title: "Bloque 5. Capital social y redes de apoyo",
    questions: [
      {
        id: "participa_capacitaciones",
        label: "21. Acostumbra a participar en capacitaciones o talleres para aprender y mejorar en su negocio?",
        type: "radio",
        options: yesSometimesNo,
      },
      {
        id: "tipos_capacitaciones",
        label: "Si respondio Si o A veces, indique en que tipos de capacitaciones ha participado:",
        type: "checkbox",
        options: ["Ventas y atencion al cliente", "Produccion o tecnicas de trabajo", "Innovacion o nuevos productos", "Administracion y contabilidad basica", "Marketing digital / redes sociales", "Otro"],
        visibleWhen: { questionId: "participa_capacitaciones", values: ["Si", "A veces"] },
      },
      {
        id: "tipos_capacitaciones_otro",
        label: "Si selecciono Otro, especifique el tipo de capacitacion:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "tipos_capacitaciones", values: ["Otro"] },
      },
      {
        id: "organizaciones_capacitacion",
        label: "22. Si respondio Si o A veces en la 21, de que tipo de organizaciones ha recibido esas capacitaciones?",
        type: "checkbox",
        options: ["Gobierno o municipio", "Universidad o institucion educativa", "ONG local", "Programas privados de emprendimiento", "Otro"],
        visibleWhen: { questionId: "participa_capacitaciones", values: ["Si", "A veces"] },
      },
      {
        id: "organizaciones_capacitacion_otro",
        label: "Si selecciono Otro, especifique la organizacion:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "organizaciones_capacitacion", values: ["Otro"] },
      },
      {
        id: "apoyo_no_capacitacion",
        label: "23. Ha recibido otro tipo de apoyo distinto a capacitaciones?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "origen_apoyo",
        label: "Si respondio Si o A veces, indique de donde provino ese apoyo:",
        type: "checkbox",
        options: ["Gobierno o municipio", "ONG local", "Universidad o institucion educativa", "Programas privados de emprendimiento", "Otro"],
        visibleWhen: { questionId: "apoyo_no_capacitacion", values: ["Si", "A veces"] },
      },
      {
        id: "origen_apoyo_otro",
        label: "Si selecciono Otro, especifique de donde provino el apoyo:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "origen_apoyo", values: ["Otro"] },
      },
      {
        id: "participa_redes",
        label: "24. Acostumbra a participar en grupos o redes de apoyo para dar a conocer su emprendimiento o conseguir contactos?",
        type: "radio",
        options: yesSometimesNo,
      },
      {
        id: "redes_participa",
        label: "Si respondio Si o A veces, indique en cuales participa:",
        type: "checkbox",
        options: ["Grupo de emprendedoras / asociacion local", "Grupo en linea", "Cooperativa o gremio", "Redes comunitarias o vecinales", "Otro"],
        visibleWhen: { questionId: "participa_redes", values: ["Si", "A veces"] },
      },
      {
        id: "redes_participa_otro",
        label: "Si selecciono Otro, especifique la red o grupo:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "redes_participa", values: ["Otro"] },
      },
    ],
  },
  {
    id: "aspectos_personales",
    title: "Bloque 6. Aspectos personales y familiares",
    questions: [
      {
        id: "equilibrio_familia_negocio",
        label: "25. Logra atender a su familia y tambien su negocio sin que uno afecte al otro?",
        type: "radio",
        required: true,
        options: ["Si", "No", "A veces"],
      },
      {
        id: "apoyo_familiar",
        label: "26. Su familia le ayuda para que usted pueda mantener su negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "tipo_apoyo_familiar",
        label: "Si respondio Si o A veces, indique de que manera le apoya su familia:",
        type: "checkbox",
        options: ["Con dinero", "Con tiempo", "Con ayuda en las tareas de la casa", "Con ayuda en el negocio", "Otro"],
        visibleWhen: { questionId: "apoyo_familiar", values: ["Si", "A veces"] },
      },
      {
        id: "tipo_apoyo_familiar_otro",
        label: "Si selecciono Otro, especifique el apoyo familiar:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "tipo_apoyo_familiar", values: ["Otro"] },
      },
      {
        id: "cuida_salud",
        label: "27. Cuida su salud mientras trabaja en el negocio?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
      {
        id: "segura_continuar",
        label: "28. Se siente con ganas y segura de seguir con su negocio aunque tenga problemas o dificultades?",
        type: "radio",
        required: true,
        options: yesSometimesNo,
      },
    ],
  },
  {
    id: "barreras_oportunidades",
    title: "Bloque 7. Barreras percibidas y oportunidades de crecimiento",
    questions: [
      {
        id: "barreras_principales",
        label: "29. Seleccione cuales considera las principales barreras que limitan el crecimiento de su negocio:",
        type: "checkbox",
        required: true,
        options: ["Acceso a financiamiento", "Burocracia y tramites", "Falta de apoyo familiar", "Poca capacitacion tecnica o administrativa", "Dificultades para acceder a clientes o mercados", "Otro"],
      },
      {
        id: "barreras_principales_otro",
        label: "Si selecciono Otro, especifique la barrera:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "barreras_principales", values: ["Otro"] },
      },
      {
        id: "oportunidades_crecimiento",
        label: "30. Seleccione cuales considera las principales oportunidades para que su negocio crezca:",
        type: "checkbox",
        required: true,
        options: ["Capacitacion o formacion en nuevas areas", "Uso de tecnologia y herramientas digitales", "Redes de apoyo o colaboracion", "Acceso a nuevos clientes o mercados", "Innovacion en productos/servicios", "Integrar elementos culturales o tradiciones", "Otro"],
      },
      {
        id: "oportunidades_crecimiento_otro",
        label: "Si selecciono Otro, especifique la oportunidad:",
        type: "text",
        required: true,
        placeholder: "Especifique",
        visibleWhen: { questionId: "oportunidades_crecimiento", values: ["Otro"] },
      },
    ],
  },
]
